Refactor/sync
friendsofagape/autographa pull request #802
Opened 2023-03-16 15:10 UTC by sijumoncy

#629  
- Refactor Sync Functionality
- New UI Implementation
- Fixing Bugs

2023-03-28 11:17 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +    }).then((res) => {
async/await mixed with promises.

2023-04-03 11:59 UTC, samueljd requested changes
Please check the async await and promises mixups. 
In case of the need to use `.then` in an sync function remove the await since that is redundant.

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +  await localForage.getItem('userProfile').then(async (user) => {
async/await mixed with promises.

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGitea.js
> +    await localForage.getItem('userProfile').then(async (user) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +      ).then((result) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +    }).then(() => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +  ).then(async (result) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +    }).then((res) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGitea.js
> +    await localForage.getItem('userProfile').then(async (user) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +      ).then((result) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Ag/SyncToGiteaUtils.js
> +    }).then(() => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/EditorSync/EditorSyncUtils.js
> +  await localForage.getItem('userProfile').then(async (user) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/ProjectMerge/MergeActions.js
> +      await fetch(urlPr, requestOptions).then((resp) => resp.json().then((data) => ({ resposne: resp, body: data })))
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/ProjectMerge/MergeActions.js
> +      .then((async (result) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/ProjectMerge/MergeActions.js
> +            await fetch(urlMerge, requestOptions).then((response) => response)
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/ProjectMerge/MergeActions.js
> +            .then(async (mergeResult) => {
.then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/ProjectMerge/MergeActions.js
> +            await fetch(result.body.html_url).then((response) => response.text())
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/ProjectMerge/ProjectMergeUtils.js
> +  .then((response) => response)
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/SyncFromGitea.js
> +    .then((response) => response.json())
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/SyncFromGitea.js
> +        .then(async (metaFile) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/SyncFromGiteaUtils.js
> +      ).then(async (result) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/Gitea/SyncFromGiteaUtils.js
> +              .then((resposne) => resposne.text())
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/hooks/useGetCurrentProjectMeta.js
> +        await localforage.getItem('userProfile').then(async (user) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/useSync.js
>      localForage.getItem('userProfile').then(async (user) => {
async/await

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/Sync/useSync.js
> +      .then(async (value) => {
await .then

2023-04-03 11:59 UTC, samueljd commented on renderer/src/components/hooks/useAddNotification.js
> +        await localforage.getItem('notification').then((value) => {
async/await

2023-04-06 04:59 UTC, vipinpaul approved these changes

2023-04-06 06:30 UTC, merged